# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vos2MCU5fDv83gg_eTBTFZAAoL8HhLTE
"""

# Pizza Order Bot
print("Hello, chatbot! Python is working.")
print("Today's date on this server:")
import datetime
print(datetime.datetime.now())

print("Bot: Hello! My name is OrderBot. What is your name?")

name = input("Customer: ")

print(f"Bot: Nice to meet you, {name}!")

print(f"Bot: That's Great, {name}")

state = "size"

while True:

    # Step 1: Get pizza size
    if state == "size":
        user_input = input("What size pizza do you want? (Small, Medium, Large): ")

        if user_input.lower() == "bye":
            print("Goodbye!")
            break

        if user_input.lower() in ["small", "medium", "large"]:
            size = user_input.capitalize()
            state = "topping"
        else:
            print("Please choose Small, Medium, or Large.")

    # Step 2: Get topping
    elif state == "topping":
        user_input = input("What topping do you want? (Pepperoni, Mushrooms, Cheese): ")

        if user_input.lower() == "bye":
            print("Goodbye!")
            break

        if user_input.lower() in ["pepperoni", "mushrooms", "cheese"]:
            topping = user_input.capitalize()
            state = "confirmation"
        else:
            print("Please choose Pepperoni, Mushrooms, or Cheese.")

    # Step 3: Confirm order
    elif state == "confirmation":
        print(f"Awesome, I have recorded a {size} {topping} pizza for you!")
        print(f"Goodbye!,{name}")
        break

